
version: 2.1

jobs:
  unit-test:

    docker:
      - image: cimg/node:16.10.0
      #- image: node


    steps:
      - checkout
      - run:
          name: "npm install"
          command: "npm install"
          #command: "echo install"
      - run: npm test
      
      - store_test_results:
          path: reports
      - store_artifacts:
         path: reports
      - store_artifacts:
           path: coverage

workflows:
  say-hello-workflow:
    jobs:
      - unit-test
