
version: 2.1

jobs:
  unit-test:

    docker:
      - image: cimg/node:16.10.0

    steps:
      - checkout
      - run:
          name: "npm install"
          command: "npm install"
      - run: npm test
#aa
      - store_test_results:
         path: reports/jest
  
      - store_artifacts:
         path: coverage

workflows:
  unit-test-workflow:
    jobs:
      - unit-test
